### ISSUE TITLE
weird issue with tap tests spread across multiple files

### ISSUE THREAD

**Issue by jokeyrhyme** [bySabi/karma-tap#10]
My project has multiple test files, each located right next to the file it tests:
- blah.js
- blah_test.js

My karma.conf.js loaded these all in:

``` js
{
  files: [ '**/*_tests.js' ],
  exclude: [ 'node_modules/**/*_tests.js' ]
}
```

These tests all use tape.

I've noticed that karma+karma-tap only cares about the test results (pass / fail) from only one of my test files. So if there are failures in the other test files, the exit code is still `0` and the run is considered a "pass".

I'm still seeing test output from all of my test files in the console, so all the tests are definitely executing.

For now, my current workaround is:
- only include 1 file in my karma.conf.js
- that test loader file has `import` / `require()` statements referencing all the original test files
- preprocess the loader file with webpack / browserify to concatenate all the files together

**Comment by romanenko** [comment]
I have exactly the same situation and thanks a lot for workaround! <3 
Is there any progress on this issue? Unfortunately, I couldn't figure out how to fix it by myself.

**Comment by tmcw** [comment]
I'm no longer using or developing this project: happy to accept a PR or transfer ownership.

**Comment by unional** [comment]
@tmcw what toolchain do you use now if you are not using karma + tap?

**Comment by tmcw** [comment]
selenium-webdriver for integration, enzyme for React components.

**Comment by unional** [comment]
@jokeyrhyme by the way, I am able to have multiple test files. I'm using with `karma-jspm`.

**Comment by bySabi** [comment]
At present time `karma-tap` is a karma "framework" adapter only then it cannot track multiple file test status. In order of implement this behaviour it must be a karma "preprocessor" adapter too. 
A PR solution about is welcome.

A current solution that worked very well is using it with `karma-webpack` like in [carma-tap-webpack](https://www.npmjs.com/package/carma-tap-webpack)  or with `karma-browserify`
