### ISSUE TITLE
new maintainer

### ISSUE THREAD

**Issue by pho3nixf1re** [bySabi/karma-tap#11]
There are several things here that need improvement. I would be willing to take over the project and maintain it. We are using tape and TAP as the basis for our JS testing. I will be opening a PR with some changes over the weekend and if that looks good to you then we can collaborate on how to do the handoff.

**Comment by tmcw** [comment]
Wonderful! I can transfer this repo to you and `npm owner add` you as well right now, if you want.

**Comment by pho3nixf1re** [comment]
That would be awesome! As long as you are willing.

**Comment by pho3nixf1re** [comment]
I've decided not to take this project over sadly. I might in the future but due to issues with karma I've decided to move our projects over to Zuul as a test runner. It seems to be much less of a hassle to work with... for now at least. Thanks for the quick response here.
