### ISSUE TITLE
 Object doesn't support property or method 'keys' IE 8

### ISSUE THREAD

**Issue by chobe** [bySabi/karma-tap#14]
Hey all,

 I'm testing my code with IE8 and I found  a problem.

![2016-04-11 12_43_43-mingw64__d_pruebas_with-tape](https://cloud.githubusercontent.com/assets/672145/14438387/21cc029a-ffe3-11e5-8fd9-9bbb0113a19d.png)

karma.config.js

![2016-04-11 12_46_05-d__pruebas_with-tape_karma config js trunk pruebas impvsupp-84 - sublime tex](https://cloud.githubusercontent.com/assets/672145/14438435/71bd3aa8-ffe3-11e5-9e8b-c821b7475853.png)

**Comment by unional** [comment]
This is not related to karma-tap. IE8 does not support `Object.keys`

**Comment by bySabi** [comment]
This issue don´t related to karma-tap.
