### ISSUE TITLE
stop at first fail

### ISSUE THREAD

**Issue by ghost** [bySabi/karma-tap#18]
is there a way to "bail" the tests?

**Comment by bySabi** [comment]
Current adapter don´t handle `bailout` event. 
a PR is welcome.

**Comment by bySabi** [comment]
add `bailout` support from `tap-parser` but at present time I don´t fine a way to generate `bailout` event for test it.

**Comment by bySabi** [comment]
closed due inactivity.

Feel free to reopen is needed
