### ISSUE TITLE
command line for package.json script

### ISSUE THREAD

**Issue by djindjic** [bySabi/karma-tap#2]
What is a command line I need to run to get results with karma-tap?
I want to run my test with testling.

**Comment by tmcw** [comment]
See [karma-tap-example](https://github.com/mapbox/karma-tap-example): this is a karma plugin, and running tests is the same as for any other karma test suite: `./node_modules/karma/bin/karma start` to start.*

(that's [what karma recommends](http://karma-runner.github.io/0.12/intro/installation.html))

**Comment by bySabi** [comment]
Making some clean ups on old issues.
