### ISSUE TITLE
2.1.1 broken - missing global ref to tapParser

### ISSUE THREAD

**Issue by traviskaufman** [bySabi/karma-tap#21]
<img width="1117" alt="screen shot 2016-08-12 at 12 23 52" src="https://cloud.githubusercontent.com/assets/1185269/17629323/bb403090-6087-11e6-9309-7afdb867a089.png">

Also see: https://travis-ci.org/google/material-design-lite/builds/151846326

**Comment by traviskaufman** [comment]
Could this because of 0926176455ef21b91001a5ba620ffd02aef500f8 removing `lib`, which means that tap-parser is no longer exported as a global variable?

**Comment by bySabi** [comment]
@traviskaufman, this PR https://github.com/tmcw-up-for-adoption/karma-tap/pull/22 should fix 'build before publish' ... let´s take a break before npm get update

**Comment by traviskaufman** [comment]
Thanks for the quick response @bySabi! For now I've pegged our version of karma-tap at `~2.0.1`; I'll change it back when #22 goes in. 😄

**Comment by bySabi** [comment]
@traviskaufman is now fixed with `2.1.3` release.

Thanks for report it
