### ISSUE TITLE
karma tape rollup karma-tap setup

### ISSUE THREAD

**Issue by thisconnect** [bySabi/karma-tap#23]
Hi

I am trying to setup `karma`, `tape`, `karma-rollup-plugin` and `karma-tap`, see test repo:
https://github.com/thisconnect/test-karma-rollup-tape

As rollup can not bundle tape ([rollup/issues/1072](https://github.com/rollup/rollup/issues/1072)) my current approach is to browserify tape first and add that to the karma files, see [karma.config.js](https://github.com/thisconnect/test-karma-rollup-tape/blob/master/karma.config.js)

The tests run fine in the browser but, as far as I understand, the tap output is not picked up by karma-tap. See screenshot below

I am new to karma and hope that I didn't miss something obvious.

![karma-browser-error](https://cloud.githubusercontent.com/assets/546900/19641301/6b6b8f1e-99e0-11e6-836a-eac0d7dffc13.png)

```
TAP version 13
adapter.js:65 # simple tape test
adapter.js:65 ok 1 foo
adapter.js:65 
adapter.js:65 1..1
adapter.js:65 # tests 1
adapter.js:65 # pass  1
adapter.js:65 
adapter.js:65 SUCCESS # simple tape test
 foo
adapter.js:65 Skipped 0 tests
adapter.js:65 # ok
adapter.js:65 
debug.js:21 Uncaught {
  "ok": true,
  "id": 1,
  "name": "foo"
}
```

**Comment by bySabi** [comment]
@thisconnect it works if you set `singleRun` to true. I don´t sure at this time is this normal or a `karma-tap-pretty-reporter`  issue or `a not implemented`

Any help welcome and thanks for repro repo, helpme a lot.

**Comment by thisconnect** [comment]
oooo... I had this config there and set to false all the time, I thought I go crazy. .. THANK YOU SO MUCH!!

**Comment by bySabi** [comment]
This line will not work with current `karma-tap-pretty-reporter`, API change on ver `3.x.x.`

```
// tapReporter: { prettifier: 'tap-spec' }
```

Now must: 

```
// tapReporter: { prettifier: require('tap-spec') }
```

**Comment by thisconnect** [comment]
yes next is to make 
- it pretty (with singleRun: true)
- and see if I get singleRun + autoWatch + karma-tap-pretty-reporter to work. 

I might open an issue for karma-tap-pretty-reporter and reference it here so you could see it. Closing this. Thanks again!!

**Comment by thisconnect** [comment]
Oh in the meantime you replied again thanks!

> This line will not work with current karma-tap-pretty-reporter, API change on ver 3.x.x.
> tapReporter: { prettifier: 'tap-spec' }
> Now must
> tapReporter: { prettifier: require('tap-spec') }

found it, it is

``` js
tapReporter: { prettify: require('tap-spec') }
```

I have updated the test repo https://github.com/thisconnect/test-karma-rollup-tape

**Comment by thisconnect** [comment]
Please feel free to fork and keep my test repo if you think it is useful for others that want to use rollup.js

**Comment by bySabi** [comment]
One last thing. If you wanna test `autowatch` mode `true`... `singleRun` must be set to `false`

**Comment by bySabi** [comment]
Add a LICENSE and update README of `test-karma-rollup-tape` and I will add to `karma-tap` example list.

**Comment by thisconnect** [comment]
> One last thing. If you wanna test autowatch mode true... singleRun must be set to false

yes I just tried that, works very nicely!

> Add a LICENSE and update README of test-karma-rollup-tape and I will add to karma-tap example list.

<strike>Ok, but I need to move it away from my thisconnect user. If you don't want it I put it on my other github user.</strike>
ignore
