### ISSUE TITLE
No file paths or sourcemaps on failing tests?

### ISSUE THREAD

**Issue by antitoxic** [bySabi/karma-tap#24]
I first submitted this to https://github.com/bySabi/karma-tap-pretty-reporter/issues/15#issuecomment-257114305

But it seems it's not their fault.

So, my failing tests come up with: "name of failure **at undefined**". I assume undefined should be a file path. But I can't get it to work.

Outputting result parameter in `this.specFailure` shows up as:

```
{ description: 'whaaat',
  success: false,
  log: [ '{\n  "operator": "fail"\n}' ],
  suite: [ '# timing test\n' ],
  time: 9 }
```

The guys from `karma-tap-pretty-reporter` pointed me to: 
https://github.com/bySabi/karma-tap/blob/master/src/adapter.js#L32

However I am not into karma plugins so I'm just looking for a solution. Is there a config I'm missing?

**Comment by bySabi** [comment]
@antitoxic it seems a source map problem. Could you isolate a failing example test with your settings.
Karma-tap is a parser on top of `tap-parser`, it only know about TAP Protocol. 

This is probably not `karma-tap` issue but a  `karma-webpack`, `tape` and `source maps`
Anyway is you share a repo I can help you to found the problem/solution

**Comment by antitoxic** [comment]
I can't share a public repo. I will try to isolate a small demo and share the code.

**Comment by bySabi** [comment]
Closed due inactivity. Feel free to open again is needed.
