### ISSUE TITLE
Cannot publish on npm repository

### ISSUE THREAD

**Issue by bySabi** [bySabi/karma-tap#27]
Hello @tmcw I cannot publish `karma-tap` updates on npm repository.
My setup is ok, I could update owned packages. 
I see that `karma-tap` is not  in my list of packages on npm profile page.

Maybe `Transfer ownership` not work on npm like here, on github.

**Comment by tmcw** [comment]
👍 I've added you with `npm owner add bysabi karma-tap`

**Comment by bySabi** [comment]
It works

Thx
