### ISSUE TITLE
Recommended reporter

### ISSUE THREAD

**Issue by facundocabrera** [bySabi/karma-tap#6]
Hey all,

I'm looking for a reporter which fits well with console and tap output, do you have any suggestions? I've tried some reporters but don't feel happy with how the output looks.

Sample of the expected output:
![sample](http://www.litixsoft.de/english/wp-content/uploads/sites/4/2014/08/screen.png)

Thanks in advance

**Comment by markogresak** [comment]
This is [mocha reporter](https://www.npmjs.com/package/karma-mocha-reporter). If you are using something like tape, I'm afraid you won't be able to produce a nested output such as this, but it gets close.

**Comment by bySabi** [comment]
I´m planning integrate prettifiers with karma-tap-reporter, https://github.com/fumiakiy/karma-tap-reporter/pull/12. 
If any one want contribute ...

**Comment by bySabi** [comment]
You can use [karma-tap-pretty-reporter](https://github.com/bySabi/karma-tap-pretty-reporter).

Example settings: https://github.com/bySabi/karma--tap--boilerplate
